# Generated by Django 3.0 on 2020-02-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraHistoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrHist', models.IntegerField()),
                ('imie', models.CharField(max_length=55)),
                ('kosc1', models.IntegerField()),
                ('kosc2', models.IntegerField()),
                ('kosc3', models.IntegerField()),
                ('kosc4', models.IntegerField()),
                ('kosc5', models.IntegerField()),
                ('ruch', models.IntegerField()),
                ('wynik', models.IntegerField()),
                ('nrGry', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GraModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrGracza', models.IntegerField()),
                ('imie', models.CharField(max_length=55)),
                ('kosc1', models.IntegerField()),
                ('kosc2', models.IntegerField()),
                ('kosc3', models.IntegerField()),
                ('kosc4', models.IntegerField()),
                ('kosc5', models.IntegerField()),
                ('ruch', models.IntegerField()),
                ('wynik', models.IntegerField()),
                ('nrGry', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GraRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrRank', models.IntegerField()),
                ('imie', models.CharField(max_length=55)),
                ('wynik', models.IntegerField()),
                ('nrGry', models.IntegerField()),
            ],
        ),
    ]
